# App Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarefas-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tarefas
  template:
    metadata:
      labels:
        app: tarefas
    spec:
      containers:
        - env:
            - name: MYSQL_DB
              value: projetodb
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: projeto-mysql-secret
                  key: password
            - name: MYSQL_USER
              value: root
          name: tarefas-site
          image: projeto-tarefas
          imagePullPolicy: Never

---
# App Servico
apiVersion: v1
kind: Service
metadata:
  name: tarefas-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: tarefas
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30001

