# Persistencia de dados
apiVersion: v1
kind: PersistentVolume
metadata:
  name: projeto-mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/projeto-tarefas"
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: projeto-mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
    
---
# MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        imagePullPolicy: Never
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: projeto-mysql-secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: projeto-mysql-data
          mountPath: /var/lib/mysql
      restartPolicy: Always
      volumes:
      - name: projeto-mysql-data
        persistentVolumeClaim:
          claimName: projeto-mysql-pv-claim
    
---
# MySQL Servico
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql